### PR TITLE
feat: add milion.js

### PR DESCRIPTION
**Pull request by ayusham001**
/resolves  [#553](https://github.com/aidenybai/million/issues/553)
/claim #553

### CODE REVIEW

**Comment by ayusham001** [comment]
hello @aidenybai 
Please review my PR and let me know if any further changes required
Thank you.

**Comment by RhysSullivan** [comment]
Hey thanks for making a PR, this project is a monorepo so MillionJS needs to be added to the main-site package in apps/main-site. It's also going to be for NextJS not vite @ayusham001

**Comment by ayusham001** [comment]
hey @RhysSullivan Thank you for clearing
I have added MillionJS to the main-site package in apps/main-site.
Please have a look into it.

**Comment by RhysSullivan** [comment]
@ayusham001 Hey I'm probably not going to be adding Million to Answer Overflow yet since it doesn't really benefit from it and I don't see a point to add more dependencies to the site if they're not needed - I'll keep this PR open to merge in the future if we end up wanting it

**Comment by ayusham001** [comment]
hello @RhysSullivan no problem with that
will I be eligible for my bounty or not?

**Pull request closed without merging**
