### PR TITLE
feat: add checkbox component

### PR DESCRIPTION
**Pull request by mrhappyma**
# Description

Add checkbox component! Yay?

## Type of change

- [X] New feature (non-breaking change which adds functionality)

# Checklist:

- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works 
- [X] I have updated .env.example if I added a new environment variable
- [X] My PR title follows the [semantic commits](https://www.conventionalcommits.org/en/v1.0.0/) style 

wow, it's a checkbox :+1:

### CODE REVIEW

**Comment by mrhappyma** [comment]
It is not allowing me to sign the CLA, the page is blank. I'm pretty sure I signed it with the docs thing anyway...

**Comment by JoltCode** [comment]
@mrhappyma yeah the CLA thing appears to be broken anyways, it was commenting on merged prs saying me and Rhys haven't signed it when I have....

**Review by RhysSullivan — APPROVED** [review]
Looks good, I think the styles might change a bit when we go to use it but it's great having the basic functionality in - nice work

For the CLA, I think the site was having some issues with that, mind checking again to see if its working now?

**Comment by RhysSullivan** [comment]
Also it looks like there's an accessibility failure in the checkbox from the tests

**Comment by JoltCode** [comment]
> Also it looks like there's an accessibility failure in the checkbox from the tests

The reason why it is failing is because of the input being by itself, and not in form, but perhaps we could wrap this in a form, with a label connected with it so we can show it works fine (accessibility wise) within a form?

**Comment by JoltCode** [comment]
@mrhappyma fyi I have altered the colors of the input backgrounds and a couple other things in the figma file, will add these input colors as tailwindCSS globals either in #242 or in a different PR

**Comment by RhysSullivan** [comment]
> The reason why it is failing is because of the input being by itself, and not in form, but perhaps we could wrap this in a form, with a label connected with it so we can show it works fine (accessibility wise) within a form?

Looks good @mrhappyma thanks for putting this together! - Last thing before we merge this is getting the tests passing, you can run them locally with yarn test in the ui package, @JoltCode suggested the way to make them pass in this case is wrapping the render() { } in a form with a label for accessibility

**Comment by mrhappyma** [comment]
Sounds good, will do 👍

**Comment by JoltCode** [comment]
I'll introduce the new background colors for the inputs in #18 (will be a tailwind global var), which should be ready to merge in a few hours or so @mrhappyma @RhysSullivan

**Comment by RhysSullivan** [comment]
Closing in favor of https://ui.shadcn.com/docs/primitives/checkbox

**Pull request closed without merging**
